/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.proyecto.pe.view;

import com.proyecto.pe.bo.EmpleadoBO;
import com.proyecto.pe.entity.Empleado;
import javax.swing.JOptionPane;

/**
 *
 * @author Favio
 */
public class FrmEmpleado extends javax.swing.JFrame {

    /**
     * Creates new form FrmEmpleado
     */
    
   private EmpleadoBO ebo = new EmpleadoBO();
    
    public FrmEmpleado() {
        initComponents();
        listarEmpleado();
        idMax();
        setLocationRelativeTo(null);
        setResizable(false);
    }

    public void idMax(){
        txt_IDEmpleado.setText(ebo.getMaxId()+"");
    }
    
    public void listarEmpleado(){
         ebo.listarEmpleado(tbEmpleado);
    }
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_IDEmpleado = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_PuestoID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_Nombres = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_Apellidos = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_DNI = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_Telefono = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_Email = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_Direccion = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txt_FecNac = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txt_FecCont = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbEmpleado = new javax.swing.JTable();
        btn_Agregar = new javax.swing.JButton();
        btn_Modificar = new javax.swing.JButton();
        btn_Eliminar = new javax.swing.JButton();
        btn_Limpiar = new javax.swing.JButton();
        btn_Salir = new javax.swing.JButton();
        btn_retroceder = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "BioMueble", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Courier New", 0, 14), new java.awt.Color(0, 51, 51))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("ID");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 20, -1));

        txt_IDEmpleado.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(txt_IDEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 140, -1));

        jLabel2.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Puesto ID");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 80, -1));

        txt_PuestoID.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(txt_PuestoID, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 140, -1));

        jLabel3.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Nombres");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 60, -1));

        txt_Nombres.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(txt_Nombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 140, -1));

        jLabel4.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Apellidos");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 80, -1));

        txt_Apellidos.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(txt_Apellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 140, -1));

        jLabel5.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("DNI");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 30, -1));

        txt_DNI.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(txt_DNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 140, -1));

        jLabel6.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Telefono");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 70, -1));

        txt_Telefono.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(txt_Telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 140, -1));

        jLabel7.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Email");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 50, -1));

        txt_Email.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(txt_Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, 140, -1));

        jLabel8.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Dirección");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 80, -1));

        txt_Direccion.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(txt_Direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 330, 140, -1));

        jLabel9.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Fec-Nac");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 70, -1));

        txt_FecNac.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(txt_FecNac, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 370, 140, -1));

        jLabel10.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Fec-Cont");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, 70, -1));

        txt_FecCont.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(txt_FecCont, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 410, 140, -1));

        jLabel11.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Formulario Empleado");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 20, 900, -1));

        tbEmpleado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbEmpleado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbEmpleadoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbEmpleado);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 50, 660, 320));

        btn_Agregar.setBackground(new java.awt.Color(0, 134, 190));
        btn_Agregar.setForeground(new java.awt.Color(255, 255, 255));
        btn_Agregar.setText("Agregar");
        btn_Agregar.setBorder(null);
        btn_Agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AgregarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 400, 80, 30));

        btn_Modificar.setBackground(new java.awt.Color(0, 134, 190));
        btn_Modificar.setForeground(new java.awt.Color(255, 255, 255));
        btn_Modificar.setText("Modificar");
        btn_Modificar.setBorder(null);
        btn_Modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ModificarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 400, 80, 30));

        btn_Eliminar.setBackground(new java.awt.Color(0, 134, 190));
        btn_Eliminar.setForeground(new java.awt.Color(255, 255, 255));
        btn_Eliminar.setText("Eliminar");
        btn_Eliminar.setBorder(null);
        btn_Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EliminarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 400, 80, 30));

        btn_Limpiar.setBackground(new java.awt.Color(0, 134, 190));
        btn_Limpiar.setForeground(new java.awt.Color(255, 255, 255));
        btn_Limpiar.setText("Limpiar");
        btn_Limpiar.setBorder(null);
        btn_Limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LimpiarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 400, 80, 30));

        btn_Salir.setBackground(new java.awt.Color(0, 134, 190));
        btn_Salir.setForeground(new java.awt.Color(255, 255, 255));
        btn_Salir.setText("Salir");
        btn_Salir.setBorder(null);
        btn_Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SalirActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 400, 80, 30));

        btn_retroceder.setBackground(new java.awt.Color(0, 134, 150));
        btn_retroceder.setForeground(new java.awt.Color(255, 255, 255));
        btn_retroceder.setText("Retroceder");
        btn_retroceder.setBorder(null);
        btn_retroceder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_retrocederActionPerformed(evt);
            }
        });
        jPanel1.add(btn_retroceder, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 420, 80, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SalirActionPerformed
        // TODO add your handling code here:
         System.exit(0);
    }//GEN-LAST:event_btn_SalirActionPerformed

    private void btn_LimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LimpiarActionPerformed
        // TODO add your handling code here:
         limpiar();
    }//GEN-LAST:event_btn_LimpiarActionPerformed

    private void btn_AgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AgregarActionPerformed
        // TODO add your handling code here:
         if(txt_IDEmpleado.getText().isEmpty() || txt_PuestoID.getText().isEmpty() || txt_Nombres.getText().isEmpty() || 
                txt_Apellidos.getText().isEmpty() || txt_DNI.getText().isEmpty()|| txt_Telefono.getText().isEmpty()
                ||txt_Email.getText().isEmpty()||txt_Direccion.getText().isEmpty()||txt_FecNac.getText().isEmpty()
                 ||txt_FecCont.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Llene todos los campos");
        }else{
            
        
            
             Empleado empleado = new Empleado();
             empleado.setEmpleado_ID(Integer.parseInt(txt_IDEmpleado.getText()));
             empleado.setPuesto_ID(Integer.parseInt(txt_PuestoID.getText()));
             empleado.setNombres(txt_Nombres.getText());
             empleado.setApellidos(txt_Apellidos.getText());
             empleado.setDni(txt_DNI.getText());
             empleado.setTelefono(txt_Telefono.getText());
             empleado.setEmail(txt_Email.getText());
             empleado.setDireccion(txt_Direccion.getText());
             empleado.setFechaNac(txt_FecNac.getText());
             empleado.setFechaContr(txt_FecCont.getText());
             
           
            String mensaje = ebo.agregarEmpleado(empleado);
            JOptionPane.showMessageDialog(null,mensaje);
            limpiar();
            listarEmpleado();
        }
    }//GEN-LAST:event_btn_AgregarActionPerformed

    private void btn_ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ModificarActionPerformed
        // TODO add your handling code here:
        
           if(txt_IDEmpleado.getText().isEmpty() || txt_PuestoID.getText().isEmpty() || txt_Nombres.getText().isEmpty() || 
                txt_Apellidos.getText().isEmpty() || txt_DNI.getText().isEmpty()|| txt_Telefono.getText().isEmpty()
                ||txt_Email.getText().isEmpty()||txt_Direccion.getText().isEmpty()||txt_FecNac.getText().isEmpty()
                 ||txt_FecCont.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Llene todos los campos");
        }else{
            
        
            
             Empleado empleado = new Empleado();
             empleado.setEmpleado_ID(Integer.parseInt(txt_IDEmpleado.getText()));
             empleado.setPuesto_ID(Integer.parseInt(txt_PuestoID.getText()));
             empleado.setNombres(txt_Nombres.getText());
             empleado.setApellidos(txt_Apellidos.getText());
             empleado.setDni(txt_DNI.getText());
             empleado.setTelefono(txt_Telefono.getText());
             empleado.setEmail(txt_Email.getText());
             empleado.setDireccion(txt_Direccion.getText());
             empleado.setFechaNac(txt_FecNac.getText());
             empleado.setFechaContr(txt_FecCont.getText());
             
           
            String mensaje = ebo.modificarEmpleado(empleado);
            JOptionPane.showMessageDialog(null,mensaje);
            limpiar();
            listarEmpleado();
        }
        
        
    }//GEN-LAST:event_btn_ModificarActionPerformed

    private void btn_EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EliminarActionPerformed
        // TODO add your handling code here:
        
         if(txt_IDEmpleado.getText().isEmpty() || txt_PuestoID.getText().isEmpty() || txt_Nombres.getText().isEmpty() || 
                txt_Apellidos.getText().isEmpty() || txt_DNI.getText().isEmpty()|| txt_Telefono.getText().isEmpty()
                ||txt_Email.getText().isEmpty()||txt_Direccion.getText().isEmpty()||txt_FecNac.getText().isEmpty()
                 ||txt_FecCont.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Llene todos los campos");
        }else{
            
        String mensaje = ebo.eliminarEmpleado(Integer.parseInt(txt_IDEmpleado.getText()));
        JOptionPane.showMessageDialog(null,mensaje);
        limpiar();
        listarEmpleado();
            
        }
        
        
    }//GEN-LAST:event_btn_EliminarActionPerformed

    private void tbEmpleadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbEmpleadoMouseClicked
        // TODO add your handling code here:
         int seleccion = tbEmpleado.rowAtPoint(evt.getPoint());
         txt_IDEmpleado.setText(tbEmpleado.getValueAt(seleccion, 0)+"");
         txt_PuestoID.setText(tbEmpleado.getValueAt(seleccion, 1)+"");
         txt_Nombres.setText(tbEmpleado.getValueAt(seleccion, 2)+"");
         txt_Apellidos.setText(tbEmpleado.getValueAt(seleccion, 3)+"");
         txt_DNI.setText(tbEmpleado.getValueAt(seleccion,4)+"");
         txt_Telefono.setText(tbEmpleado.getValueAt(seleccion,5)+"");
         txt_Email.setText(tbEmpleado.getValueAt(seleccion, 6)+"");
         txt_Direccion.setText(tbEmpleado.getValueAt(seleccion,7)+"");
         txt_FecNac.setText(tbEmpleado.getValueAt(seleccion,8)+"");
         txt_FecCont.setText(tbEmpleado.getValueAt(seleccion,9)+"");
    }//GEN-LAST:event_tbEmpleadoMouseClicked

    private void btn_retrocederActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_retrocederActionPerformed
        // TODO add your handling code here:
        FrmMueble vista = new FrmMueble();
        vista.setVisible(true);
        vista.setLocationRelativeTo(null);
        vista.setResizable(false);
        vista.setTitle("Crud-Mueble");
        this.setVisible(false);
    }//GEN-LAST:event_btn_retrocederActionPerformed

     
   public void limpiar(){
        txt_IDEmpleado.setText("");
        txt_PuestoID.setText("");
        txt_Nombres.setText("");
        txt_Apellidos.setText("");
        txt_DNI.setText("");
        txt_Telefono.setText("");
        txt_Email.setText("");
        txt_Direccion.setText("");
        txt_FecNac.setText("");
        txt_FecCont.setText("");
        idMax();
    } 
   
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmEmpleado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Agregar;
    private javax.swing.JButton btn_Eliminar;
    private javax.swing.JButton btn_Limpiar;
    private javax.swing.JButton btn_Modificar;
    private javax.swing.JButton btn_Salir;
    private javax.swing.JButton btn_retroceder;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbEmpleado;
    private javax.swing.JTextField txt_Apellidos;
    private javax.swing.JTextField txt_DNI;
    private javax.swing.JTextField txt_Direccion;
    private javax.swing.JTextField txt_Email;
    private javax.swing.JTextField txt_FecCont;
    private javax.swing.JTextField txt_FecNac;
    private javax.swing.JTextField txt_IDEmpleado;
    private javax.swing.JTextField txt_Nombres;
    private javax.swing.JTextField txt_PuestoID;
    private javax.swing.JTextField txt_Telefono;
    // End of variables declaration//GEN-END:variables
}
